############################################################
#
# liboptimg Makefile
# Generated by amyznikov Nov 8, 2016
#
############################################################

SHELL = /bin/bash

TARGET = align-retina-images

all: $(TARGET)


ifeq ($(OS),Windows_NT)
SYS_INCLUDES = -I/c/msys64/usr/include -I/c/msys64/mingw64/include
SYS_LIBDIR = /c/msys64/mingw64/lib
DEFINES += -D__USE_MINGW_ANSI_STDIO=1 -D_USE_MATH_DEFINES=1
endif

cross   =
sysroot =
DESTDIR =
prefix  = /usr/local
bindir  = $(prefix)/bin
incdir  = $(prefix)/include
libdir  = $(prefix)/lib


INCLUDES+= -I. -I$(CURDIR)/../../include $(SYS_INCLUDES)
SOURCES = $(wildcard *.c *.cc)
HEADERS = $(wildcard *.h)
MODULES = $(foreach s,$(SOURCES),$(addsuffix .o,$(basename $(s))))


# C preprocessor flags
CPPFLAGS=$(DEFINES) $(INCLUDES)

# C Compiler and flags
CC = $(cross)gcc -std=c11
CFLAGS= -Wall -Wextra -O3 -g0

# C++ Compiler and flags
CXX = $(cross)g++ -std=c++11
CXXFLAGS = $(CFLAGS)


# Loader Flags And Libraries
LD=$(CXX)
LDFLAGS = $(CXXFLAGS)

# STRIP = $(cross)strip --strip-all
STRIP = @echo "don't strip "

#   videoio xfeatures2d features2d
OPENCVLIBS = tracking video xfeatures2d features2d imgproc imgcodecs core 
ifeq ($(OS),Windows_NT)
LIBOPENCV = $(addprefix $(SYS_LIBDIR)/libopencv_, $(addsuffix 310.dll.a, $(OPENCVLIBS)))
else
LIBOPENCV = $(addprefix -lopencv_,$(OPENCVLIBS))
endif

LDLIBS += $(LIBOPENCV) -lstdc++ -lpthread


#########################################


$(MODULES): $(HEADERS) Makefile
$(TARGET) : $(MODULES) Makefile
	$(LD) $(LDFLAGS) $(MODULES) $(LDLIBS) -o $@

clean:
	$(RM) $(MODULES)

distclean: clean
	$(RM) $(TARGET)

install: $(TARGET) $(DESTDIR)/$(bindir)
	$(STRIP) --strip-all $(TARGET) && cp $(TARGET) $(DESTDIR)/$(bindir)

uninstall:
	$(RM) $(DESTDIR)/$(bindir)/$(TARGET)


$(DESTDIR)/$(bindir):
	mkdir -p $@
